### ISSUE TITLE
Map specific fps loss ?

### ISSUE THREAD

**Issue by Panjoo** [jdolan/quetoo#252] opened 2016-11-05 16:33 UTC
After installing the latest (win32 minGW) build from the site some maps suddenly perfrom very poorly. I was doing some more testing with the map Lavatomb and its buggy rotator :gear: thing. At first when I saw my fps counter I thought that my frames got capped or something but after running around I noticed it wasn't locked, just very low all of a sudden. Then loaded other maps and those seemed to not be affected at first glance but to be sure I would need to compare fps on all maps.

![stealingmyfps](https://cloud.githubusercontent.com/assets/10857572/20031745/b5dd7d82-a37c-11e6-908a-903f457d90a4.jpg)

Uh oh!

**Comment by jdolan** [comment] 2016-11-05 18:34
@Paril refactored the renderer to be completely OpenGL 2.0 compliant, and that was merged in on October 27th. So that seems to coincide with this issue.

Would you mind starting the game with `+set verbose 1 +cvar_list` and pasting the output here?

**Comment by Paril** [comment] 2016-11-05 18:39
The only thing I can think of that would have changed between those two scenes is the lava balls and only in a very recent commit, since the old lava balls created way too many particles at high FPS, but that wouldn't explain your FPS being worse since the commit. BSP rendering is the worst area of the game (as it should be) but that system has changed very little since the refactor.

@jdolan I think we should start including the commit ID in our config.h as part of the build string too. It'd be really handy in a case where we have to test regressions and to be sure people are on latest versions.

**Comment by jdolan** [comment] 2016-11-05 18:44
Btw @Panjoo with the latest 60hz changes, the recommended setup for all players is to enable vsync (`r_swap_interval 1`) and remove your frame limiter (`cl_max_fps 0`). These are now the defaults. I was able to restructure how Quake samples input and predicts movement, and all of the implicit latency that is typically associated with enabling vsync is now gone. And because the server now runs at 60hz, running your client at 60hz or 120hz is also ideal. It will guarantee that your server frames run every 16ms in lock step with your client. Please let me know how that works for you.

But of course.. we need to figure out how your performance dropped so dramatically with the GL 2.0 stuff. I wonder if your card / driver does not do well with indexed arrays or something.

**Comment by Paril** [comment] 2016-11-05 18:44
Indexed arrays is my only guess. I wonder if we can provide him with a build of pre-indexed-arrays and see if that works well for him?

**Comment by jdolan** [comment] 2016-11-05 18:48
Aaaand therein lies the peril (see what I did there) of "squash and merge." All of the `feature/gl30` commits are now one. There's no easy / automated way to cherry pick GL 2.0 when we were still using flat arrays.

**Comment by Paril** [comment] 2016-11-05 18:48
I still have my local commits, I can un-cherrypick if need be.

**Comment by jdolan** [comment] 2016-11-05 18:50
Oh -- thankfully we didn't delete that branch! It's still there. Here is the commit that introduced indexed arrays for BSP: 6590e227dd4dba5821a7009d012889c727996633

https://github.com/jdolan/quetoo/commits/feature/gl30

**Comment by Paril** [comment] 2016-11-05 18:50
I undid that commit though, remember? You said it drastically reduced FPS, and you were right.

**Comment by jdolan** [comment] 2016-11-05 18:51
No, you reverted triangle soup (`GL_TRIANGLES`). We kept indexed arrays.

**Comment by Paril** [comment] 2016-11-05 18:52
Oh right. Well, here's part 1 of 2 of my tests: a screenshot of me in lavatomb. http://i.imgur.com/YqojofA.jpg

I'm going to pull the commit before GL20 and compare.

**Comment by Paril** [comment] 2016-11-05 18:58
And from commit before gl20 was a thing: http://i.imgur.com/PtPgC5s.jpg

I am having the exact same FPS (within accepted tolerance) in the same area.. so it must be something more specific to your setup.

**Comment by Paril** [comment] 2016-11-05 19:01
Okay, so this is from before gl20: http://i.imgur.com/yJcrsnX.jpg

I'm honestly surprised that it's this different from the fixed pipeline branch. I did a lot of profiling on the new stuff and GL is rarely there on the top, not to mention the numerous fixes I did to extraneous state changes and the like..

**Comment by Paril** [comment] 2016-11-05 20:57
I have identified the issue and am working to fix this.

**Comment by Panjoo** [comment] 2016-11-05 21:44
Good to hear that Paril, I was starting to sweat a little.

--
> **jdolan:** Would you mind starting the game with +set verbose 1 +cvar_list and pasting the output here?

Sure, but how do I copy the output, lol! Don't know the condump command. Do I also have to load up a map or just the game?

Well, the performance drop isn't just on lavatomb but it seems the worst there, at least on my pc. It sometimes drops to 30-40, I hate how laggy that feels! Also the hyperblaster firing rate is affected which messes up the hyperclimbing, it goes very slow even on maps where my fps is still okay-ish.

I also enabled vsync but the game feels too sluggish right now so I can't really say I notice any difference.

**Comment by Paril** [comment] 2016-11-05 22:09
@jdolan what do you think about a) implementing log system for console, would be helpful for servers but also client issues like this (could even have verbose stuff go to log even if it's disabled in client!) b) adding commit ID to build string?

**Comment by Paril** [comment] 2016-11-06 07:03
I pushed one half of the fix. Material system now uploads all of the material surfaces in one batch and then draws them in the second batch - it improves my FPS by about 40 in lava areas on lavatomb. I notice that entity materials cause lag still, which is weird, but I am looking into it.

**Comment by Panjoo** [comment] 2016-11-06 10:59
> ...the issue is related to materials. Can you set r_materials 0 and see if that fixes it? For me, it doubles my FPS.

Yes you're right, setting r_materials 0 makes the fps shoot back up, in some places almost 4 or 5 times higher.

**Comment by jdolan** [comment] 2016-11-06 13:02
Not a bad idea, @Paril. But for now, the console does have a dump command, it's called `dump <file>`. By default, it writes to `console.log`. Please update before using this function.

**Comment by Paril** [comment] 2016-11-06 18:20
I made some more changes, can you try @Panjoo and see how better it is?

**Comment by Panjoo** [comment] 2016-11-06 22:28
Maybe I'm imagining things but it looks as if I'm getting some more frames now than before, feels pretty steady. Also tested a bit on other maps.

Only problem now is that not all stages of the *lava texture material are showing. The scrolling fx is what makes the lava come to life and I'm not seeing it anymore. Without any movement the whole thing look a lot less convincing.

*
{
material lavatomb/brlava
	{
	texture lavatomb/brlava1
	blend GL_SRC_ALPHA GL_ONE
	scroll.s -0.02
	}
{
	texture lavatomb/brlava1
	blend GL_ONE GL_ONE
	scroll.t 0.02
	}
}

**Comment by Paril** [comment] 2016-11-07 00:12
Yep I am aware of this one. I just noticed it accidentally, ha. I'm fixing it.

**Comment by Paril** [comment] 2016-11-07 00:25
Should be fixed now. Try latest build in about 15 min.

**Comment by Panjoo** [comment] 2016-11-07 18:12
Hey nice going man, all is back to normal now and it feels like an improvement, fps-wise.
:+1:

**Comment by Paril** [comment] 2016-11-07 19:38
Still more improvements to go!

**Comment by Panjoo** [comment] 2016-11-11 19:26
Just noticed that my weapon glow skins don't want to show up anymore. Doing r_materials only enables/disables the texture effects in the map but not the skins, at least that's how it seems. Or maybe there's another cvar that I'm missing?

**Comment by Paril** [comment] 2016-11-11 19:31
I broke it in master but it is fixed in gl-types branch. It'll be merging soon.

**Comment by jdolan** [comment] 2016-11-12 04:12
I think we can close this out now. @Panjoo agree?

**Closed** 2016-11-12 14:03 UTC
Labels: os:windows, question

**Comment by Panjoo** [comment] 2016-11-12 19:43
@jdolan Yes Sir!
