### ISSUE TITLE
RG doesn't affect stainmap on a moving platform

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo#435] opened 2017-02-20 02:58 UTC
Shooting RG onto the platfrom on edge while riding it up (shooting from on it) doesn't leave a mark on the platform, while riding it down leaves a smaller mark then should be left.

**Comment by Paril** [comment] 2017-02-20 11:55
I think this is regression from @jdolan's fix to rocket stains disappearing, since I tested this heavily when I worked on mover stains.

**Comment by jdolan** [comment] 2017-02-20 12:22
Er.. got a revision number? I don't even remember rockets disappearing.

**Comment by jdolan** [comment] 2017-02-21 02:42
This is purely a consequence of the lightmap resolution of that platform, and of the size of the railgun stain (which is small). Set `r_draw_bsp_lightmap 1` and shoot the platform from anywhere -- on it or not, stationary or not. The railgun won't leave a mark, the RL and HB do.

**Comment by Paril** [comment] 2017-02-21 10:51
Am going to disagree - every stain always modifies at least 1 pixel. If a pixel is not being touched when you're riding up an elevator then there is indeed a bug. This worked fine when I tested it during our change to luxel-space stains, and it seems that bullet holes work fine.. but @jdolan recently changed the way rockets, blasters, and hyperblasters leave their stains. Not sure why railgun seems to be affected though since it has a fairly large radius.

72f65556d5f58fb3b58b8fd186e72183607e10f2 was the only recent commit that played with the projections of projectiles. If anybody has time, can they test the commit before it and see if you can produce "expected" results?

**Comment by jdolan** [comment] 2017-02-21 14:15
I'll re-open if you want to investigate, but the commit you referenced does not touch the railgun at all :/

**Comment by Paril** [comment] 2017-02-21 14:17
Yeah I know, hitscan weapons shouldn't have been affected - bullets on movers seem to work fine. I'm very confused as to how this all could happen to be honest.

**Comment by jdolan** [comment] 2017-03-08 13:07
Is this possibly related to the stain "jumping" we've discussed over Discord? Flawed (eagerly optimized) distance check?

**Comment by Paril** [comment] 2017-03-23 06:41
I can't reproduce this any more, at least at 60 or 120 fps on edge, HOWEVER there is now a bug where shooting a rocket on top of edge elevator *when it is at its top-most state* it doesn't leave a stain. :(

**Comment by Paril** [comment] 2017-03-23 06:54
I fixed by removing the trace check, which was kinda overkill anyways.

**Closed** 2017-03-23 06:54 UTC
Labels: bug:minor
