### ISSUE TITLE
cl_editor is broken, again

### ISSUE THREAD

**Issue by Panjoo** [jdolan/quetoo#512] opened 2017-11-04 16:19 UTC
The sliders are not responding and the normalmap texture name isn't showing.

Now normally I would just fall back on a rather old quake2world build that I kept just for its functioning material editor. Unfortunately the Hdd which had a lot of my quetoo backup stuff decided to give up the ghost without warning and so I've lost alot of shit including that old quake2world version. But I need a working cl_editor and at this moment I have none :(

**Comment by jdolan** [comment] 2017-11-05 02:11
I can reproduce this. I'll take a look at it in the morning. Sorry bud.

**Comment by jdolan** [comment] 2017-11-05 12:45
This is fixed, please close out when you can confirm.

**Comment by Panjoo** [comment] 2017-11-05 19:23
I updated to 316a26a: Still no luck when I try to use the sliders, nothing moves. 

On alt+tab I see this;
![nope](https://user-images.githubusercontent.com/10857572/32418239-42a3d2e4-c266-11e7-83f7-82af86a8cd52.jpg)

Also tried it in windowed mode but still nothing.

**Comment by jdolan** [comment] 2017-11-05 20:06
My bad, Pan. I pushed the fix to the wrong branch. I've just merged the fix into master. Should be available in 5 minutes.

**Comment by Panjoo** [comment] 2017-11-05 21:20
Okay so the editor seems to work now (nice 1), but when I click 'Save' the game crashes with a Signal 11...

**Comment by jdolan** [comment] 2017-11-05 22:00
Ugh. Fixed.

**Comment by Panjoo** [comment] 2017-11-05 23:08
Okay I stop because I'm getting crazy here. Maybe we should not try to hurry this. 

Save button works, but now I can no longer compile the map I'm working on, 
![tiring](https://user-images.githubusercontent.com/10857572/32420074-69a095c0-c285-11e7-8ee1-01ce48ed1273.jpg)

I figured maybe the map's title being rather long was the problem (but that had been fixed), but even after changing the title the map refuses to compile. Some other map files I tested were no problem.

**Comment by jdolan** [comment] 2017-11-05 23:09
Wanna attach your .map?

**Comment by Panjoo** [comment] 2017-11-05 23:18
Ehm no, not really. No spoilers, lol.

I saved the map under a different name and it compiles...
however, trying to load the map just crashes quetoo.

I'll just try some more things tomorrow when my head is clear again. I'm done for now, sorry.

**Comment by Panjoo** [comment] 2017-11-06 15:25
On further inspection I found that something (quemap?) had cleared out the material file of my map. It was totally empty (0bytes)
And when I try to let quemap create a fresh .mat file it also just crashes with Signal 11

After I copied&pasted a backup .mat file of the map, it compiles and loads with no problems.

(P.S. When I drag the cl_editor window to the sides, the sliders don't work.)

**Comment by jdolan** [comment] 2017-11-06 19:47
So.. when the Save button was broken, it nuked your materials file. Sorry about that. It's fixed.

Crashing when creating a fresh .mat file.. I can't reproduce that one right now. I _might_ need your .map / .bsp to figure that one out. It's working fine for me.

Fixing the editor so that it can be moved around, I will look at tonight. I've been elbow-deep in MVC, anyway ;)

Thanks for riding these bumps out.

**Comment by Panjoo** [comment] 2017-11-07 22:30
> **jdolan:** Crashing when creating a fresh .mat file.. I can't reproduce that one right now.

There probably was nothing wrong with the `-mat` option, sigh! Must have been the nuked .mat file that was causing it to crash because it's working fine again. 
Once I had restored my backup .mat file, I didn't try to create a new .mat file since the map would load up again and that was my main concern. So, you can close this if you want.

**Comment by jdolan** [comment] 2017-11-08 11:14
Thanks Pan. I'm going to keep this one open until I remember to fix the editor / moving it around bug.

**Comment by jdolan** [comment] 2018-02-09 23:43
The editor is completely fixed now.

**Closed by jdolan** 2018-02-09 23:43 UTC
Labels: bug:minor, in progress
