### ISSUE TITLE
Quemap bugs/oddities

### ISSUE THREAD

**Issue by SpineyPete** [jdolan/quetoo#524] opened 2018-02-11 20:56 UTC
So I've been zipping up some maps. The missing materials have been resolved. Right now I'm having two other issues:

- [ ] Filename truncation on exported .pk3, more specifically it's only showing the first 12 chars of the name. I've tried quemap.exe -zip "c:\location\dir\example", but that doesn't seem to work? @jdolan

- [x] Missing textures, it does not export all textures for some reason. While exporting Gehenna just now it's missing the last 4. @jdolan

 - [x] lightmap_scale needs to be fed a value of 1/2^n, right now this is a float, which is error prone and unintuitive. Other values are accepted but produce garbled output. @jdolan

- [x] there's some black pixel "shadow leakage" along edges of the lightmaps, it might be worth the time to consider if those can be fixed or optimized somehow (padding? conservative sampling?) -- and whether they're in fact a bug or not. @void-995 could you peek at this one?

- [x] Check if there's any reason nowadays to subdivide maps and/or cull that code. It seems to have been done for software rendering originally. @jdolan

- [x] Should hint brushes split leafs? That seems couple the rendering more tightly to the vis, which makes the vis tighter but also generates more complex geometry. This might seperate data to be fed to the BSP process?

- [x] If there's a way to not make detail brushes cause splits, that would be great, now you have to be rather mindful of them. @jdolan

I'll do some more digging around to see if I can narrow it down.

**Comment by jdolan** [comment] 2018-02-11 21:40
@Paril I'm not seeing this on OS X. Could you step through this a bit on Winders?

**Comment by jdolan** [comment] 2018-02-11 21:42
@SpineyPete Could you give a concrete test case for this? And of that test case, which textures are missing?

**Comment by SpineyPete** [comment] 2018-02-13 23:23
So this turned out to be an issue with path length and/or other string shenanigans. Using -w with a shorter path fixed both issues.

I also noticed that when I put a number behind -antialias it causes the zipping of certain textures to fail on some (not all) maps because of what appears at least in the console output to be a garbled filename. Might be related to the above, or might not be -- haven't tried narrowing it down further.

**Comment by SpineyPete** [comment] 2018-02-13 23:31
* lightmap_scale needs to be fed a value of 1/2^n, right now this is a float, which is error prone and unintuitive. Other values are accepted but produce garbled output.
* there's some black pixel "shadow leakage" along edges of the lightmaps, it might be worth the time to consider if those can be fixed or optimized somehow (padding? conservative sampling?) -- and whether they're in fact a bug or not.

**Comment by jdolan** [comment] 2018-02-14 01:38
Ambient light is a worldspawn key and could be simply passed to the shader, rather than baked into lightmaps. This would likely produce less banding in the lightmaps.

**Comment by SpineyPete** [comment] 2018-02-14 13:17
### Path issue

Faulty path: "C:\Users\Eigenaar\Documents\My Games\Quetoo\default\maps" (including quotes)
Fixed path: "C:\Games\Quetoo\share\default\maps" (including quotes)

### Phong seams

Here's the normals, they appear correct to me.

![quetoo014](https://user-images.githubusercontent.com/28701157/36204368-579b63c8-118b-11e8-8066-6715533ae75b.png)

The seams are still visible also when a texture is applied. Even if the surface normals might be interpolated correctly, the lightmap color and deluxemap is still being sampled.

That said, look at the corner where the ceilings meet. While the ceiling is curved and should be interpolated, that corner should NOT be interpolated. Unfortunately, because all these faces touch eachother, there's no way at the moment to prevent that from happening. Other compilers and authoring tools supply a maximum-phong-angle parameter, smoothing groups or edge flags.

Edge flags are problematic with map files and editor support. The phong maximum angle is a set-it-and-forget-it solution, which could cover the majority of cases for the average map. I think that smoothing groups could be implemented by simply having multiple phong flags instead of just one. Considering the 4-color-theorem, you should have at least 4, but having at least 5 or 6 would be desirable I think. Smoothing groups would allow the issue to be fixed manually in all cases.

### Shadow leakage seams

I noticed some other interesting artifacts:

![quetoo015](https://user-images.githubusercontent.com/28701157/36204452-9e7d6cc8-118b-11e8-8cad-d466453f9e28.png)
Notice how the pixel lighting seems to jump back-and-forth along the edge.

I have a hunch all of this weirdness (including phong) might be due to how the texels are sampled. Sampling only the center of the texel can result in texels being missed along edges. Instead they should be sampled in a *conservative* manner.

![samplepointfix_03](https://user-images.githubusercontent.com/28701157/36204952-55598156-118d-11e8-8316-dbed65686465.png)
![samplepointfix_01](https://user-images.githubusercontent.com/28701157/36204955-598c80ac-118d-11e8-8e14-fc65ec9b34c8.png)
![samplepointfix_02](https://user-images.githubusercontent.com/28701157/36204956-59a53714-118d-11e8-814f-51149973edd5.png)

### Optimization idea

On a sidenote, now that the possibility of decoupling lightmap resolution is being investigated, this optimization seems like a Good Idea to consider? Storing full res lightmaps for faces that only have blurry gradients seems wasteful.

![halo3lightmap01](https://user-images.githubusercontent.com/28701157/36204125-45d73d48-118a-11e8-877a-6ad47e069ce4.jpg)
![halo3lightmap02](https://user-images.githubusercontent.com/28701157/36204127-45f35ae6-118a-11e8-8829-84a7d8030cc0.jpg)
![halo3lightmap03](https://user-images.githubusercontent.com/28701157/36204128-460e5d28-118a-11e8-93a9-c42d00d2c449.jpg)

**Comment by SpineyPete** [comment] 2018-02-21 16:01
* Check if there's any reason nowadays to subdivide maps and/or cull that code. It seems to have been done for software rendering originally.

**Comment by jdolan** [comment] 2018-02-23 03:59
@SpineyPete `quemap -zip` missing some textures (material stages) has been fixed. For the truncated filename issue, could you give me the full command line that caused this issue? Are you invoking it through GtkRadiant (which passes absolute paths), or at a command prompt (where you might be giving it relative paths or "Quake paths)?

**Comment by SpineyPete** [comment] 2018-02-23 11:47
(Touchscreen accident ... :/)

Used absolute paths on commandline, paths are at the top of my lengthy comment. Used -bsp -vis -light -antialias -zip. Providing a write path solved it (with shorter path... I think? Now that I think about it I haven’t tried giving it the old one)

I can give the full batch file if you think that would be useful.

**Comment by jdolan** [comment] 2018-02-23 12:45
Yes, please provide your .bat file. I can't reproduce this on OS X with really long path names. I did also push a minor fix last night where we were accessing `dirname` after freeing it, which _could_ have been problematic. So if you could re-test and attach your .bat file if the bug is still present, that'd be helpful. For what it's worth, here is my passing test-case:

```
$ mkdir -p /tmp/foo/bar/baz/really-long-path/this-should-do-it/no-seriously-long-path/abcdefghijklmnop
$ cp ~/.quetoo/default/maps/lighttest.map /tmp/foo/bar/baz/really-long-path/this-should-do-it/no-seriously-long-path/abcdefghijklmnop
$ quemap -bsp -vis -light -zip /tmp/foo/bar/baz/really-long-path/this-should-do-it/no-seriously-long-path/abcdefghijklmnop/lighttest.map
```

Successfully authors `/Users/jdolan/.quetoo/default/map-lighttest-13651.pk3`

**Comment by jdolan** [comment] 2018-02-23 12:48
Also, btw @SpineyPete, `quemap` _expects_ Quake paths (e.g. `maps/my.map`) on the command line. The per-user directory you were issuing the full path to _is already on the default search path_. Quemap does support absolute path references, because that's what *Radiant will give it. But if you are compiling via .bat file, and your .map files reside in `My Games\Quetoo\default\maps` (like they should), then just pass `quemap [options] maps/my.map`

**Comment by SpineyPete** [comment] 2018-02-23 13:26
Oh, I didn't know that, been using Radiant till recently.

Here's the contents of the batch file:

```
@echo off
echo QUEMAP
echo ------
echo press CRTL-C to exit
echo.

:COMPILE

set src1=C:\Games\Quetoo\share\default
set src2=\maps
set /p src3=Filename of map to compile: 
set src4=.map
set srcpath=%src1%%src2%\%src3%%src4%

echo ----
echo File to be read:    %srcpath%
echo File to be written: %src1%%src2%\%src3%.bsp

echo ----
set options1=-bsp -vis -light
echo Quemap arguments: %options1%
set /p options2=Provide additional arguments if necessary: 

echo ----
cd "C:\Games\Quetoo\bin\"
quemap.exe -w "%src1%" %options1% %options2% "%srcpath%"

goto COMPILE

```

For final ones I type in -antialias -zip in the additional parameters.

**Comment by jdolan** [comment] 2018-03-15 18:06
Re: altering `CONTENTS_DETAIL` so that it never splits structural brushes, I think the spot to do that is here: https://github.com/jdolan/quetoo/blob/lightmap-texture-arrays/src/tools/quemap/brush.c#L517

**Comment by jdolan** [comment] 2019-05-20 11:00
Closing this out as all of these issues are addressed in `brave-new-world` :)

**Closed by jdolan** 2019-05-20 11:00 UTC
Labels: bug:minor, component:quemap
