### ISSUE TITLE
Particles cause tear lines on maps

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo#253] opened 2016-11-06 03:08 UTC
See attached screen shots, GL20 related.

![quetoo032](https://cloud.githubusercontent.com/assets/567688/20035085/54141950-a393-11e6-9166-e5b756bbd09d.png)
![quetoo033](https://cloud.githubusercontent.com/assets/567688/20035087/54262ffa-a393-11e6-9626-8c592581ca95.png)

**Comment by Paril** [comment] 2016-11-06 03:51
Wat de fook are those? Is mipmapping enabled? This would be atlas-related.

**Comment by jdolan** [comment] 2016-11-12 04:11
This is fixed in master. Nice one @Paril

**Comment by Paril** [comment] 2016-11-12 04:19
This is actually still a problem, I didn't do this yet. Sorry! It's my next job :)

**Comment by jdolan** [comment] 2016-11-12 04:20
Oh, weird! I saw it this evening very plainly, and then could not reproduce it just now with your latest changes.

**Comment by Paril** [comment] 2016-11-12 04:26
It's -possible- that diffuse being uint16 fixes this indirectly, but I still want to be sure I introduce a way to disable atlasing in the case where the mipmapping fails like this down the road.

**Comment by Paril** [comment] 2016-11-14 06:10
Fixed in latest commits.

**Closed** 2016-11-14 06:10 UTC
Labels: bug:minor
