### ISSUE TITLE
Geometry seams when multisampling is enabled.

### ISSUE THREAD

**Issue by SpineyPete** [jdolan/quetoo#517] opened 2017-12-25 01:03 UTC
Can anyone reproduce this?

The moment I enable multisampling these cracks start appearing on grazing angles. On both nVidia and Intel.

![quetoo025](https://user-images.githubusercontent.com/28701157/34329960-69d924fc-e914-11e7-963a-19e1c9b9cf20.png)
![quetoo026](https://user-images.githubusercontent.com/28701157/34329961-69f4e50c-e914-11e7-9d1e-d16374e8c111.png)
![quetoo027](https://user-images.githubusercontent.com/28701157/34329962-6a10d294-e914-11e7-84d1-ce894adcc645.png)
![quetoo028](https://user-images.githubusercontent.com/28701157/34329963-6a2bd94a-e914-11e7-99dd-9009e76f6b8f.png)

They're in all the maps, though they're much less noticable in the official ones (they're there if you look closely).

Could be an issue with UV coords or lightmap undersampling?

**Comment by kaadmy** [comment] 2017-12-25 01:05
Not sure about this, but is this due to mipmaps/lightmap as you said above? Maybe try putting anisotropy on highest/off to see if it changes?

**Comment by Paril** [comment] 2017-12-25 01:18
No, our geometry had always had this bug. Faces of map geometry have thin gaps in them for no apparent reason. Have not been able to figure out why.

**Comment by ptrvrhvn** [comment] 2017-12-25 11:05
Anisotropy doesn’t change things.
By the way, what are the factors that determine whether a face gets split?
It’s not a rounding or precision error?

**Comment by Calinou** [comment] 2017-12-25 11:57
Perhaps it's an issue with some kind of polygon offset value?

**Comment by Paril** [comment] 2017-12-25 14:16
The face splitting is on the BSP subdivision boundary (check wireframe). Not rounding/precision because they're often on integer boundary and the data is fine in the gpu. Polygon offset is only used for materials

**Comment by jdolan** [comment] 2018-01-16 18:19
Is this _only_ with multisample enabled? I feel like I've seen "holes" (single white pixels) in geometry even without MSAA enabled. But I could be mistaken..

Would adopting FXAA in our shader path, and removing the SDL multisample code, fix this?

**Comment by Paril** [comment] 2018-01-16 18:35
Not related to multisampling. Happens all the time. FXAA would not fix it since it just blurs the final result, and the final result is what has the white pixels.

**Comment by ptrvrhvn** [comment] 2018-01-16 18:37
I only see it with multisampling enabled... ¯\_(ツ)_/¯
It's true the sky helps a lot.

**Comment by Paril** [comment] 2018-01-16 18:38
No no, the sky is what the white pixels are. You're seeing the sky through the walls; you are not seeing it on other parts because behind that wall is whatever was in the framebuffer before, which will be the color of the wall pixels next to it in most cases. If you turned gl_clear on and set the clear color to white/red you'll see the pixels everywhere.

You see it more on multisampling because there will be more pixels exposed.

**Comment by ptrvrhvn** [comment] 2018-01-16 18:40
Just that I'm not asking annoying questions: what are the possible causes that you've ruled out?

**Comment by Paril** [comment] 2018-01-16 18:44
I checked the depth buffer, but our points aren't large enough for the depth buffer to be causing issues.
The points in the GPU are mostly snapped on integral points; even if they weren't, we use elements + GL_TRIANGLE_FAN/STRIP for BSP polygons, so it can't be the points positions being not pixel perfect to each other. It occurs on seams between actual pieces inside the strip, too, not just adjacent brush faces.

**Comment by ptrvrhvn** [comment] 2018-01-16 19:03
Just thinking about it a bit (I barely know what I'm talking about anyway).

I guess the pixel center gets missed by some infinitesimal amount during rasterization? That would explain why it becomes more visible with multisampling.
Alternatively, maybe there's something wrong with the order in which the depthbuffer reads/writes happen, or some pixel depths get overwritten/corrupted for whatever reason, but it would be weird that that only happens on edges.
I wonder if a vertex is laying on an edge of a neighboring triangle, that it's pixel position is different from the corresponding pixel on the edge, because the latter uses an interpolated value? I believe most engines generally sew t-junctions in geometry together for that reason. Then again, it happening on triangles inside the strip is just weird.

**Comment by Paril** [comment] 2018-01-16 19:16
Geometry shouldn't show pixels on the seams as long as the positions are correct; I've written a lot of OpenGL stuff and have never seen pixels peak through edges like it does here, so it must be something odd we're doing that's causing it.

Unsure if the issue is at rasterization stage, but it's worth looking into. Maybe we can set the fp to highp in shaders and see if it fixes it?

Unlikely to be depth buffer. The sky is visible behind the geometry, and the sky in the depth buffer is gonna be wayyyy out there. It's rendered before world geometry.

**Comment by jdolan** [comment] 2018-02-09 02:51
So @Paril @void-995 and @SpineyPete figured out that this is due to bad T-juncs, and me being a donkey. The fix is in, but all maps need to be recompiled. Fortunately, we're introducing new lightmap formats that will require a recompile of all maps anyway!

**Closed by jdolan** 2018-02-09 02:51 UTC
Labels: bug:minor
