### ISSUE TITLE
Team scoreboard overlap (regression)

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#462] opened 2017-03-27 00:59 UTC
With two populated teams and one spectator (not sure if spectator matters), the teams scoreboard has some rendering overlap:

![quetoo014](https://cloud.githubusercontent.com/assets/643118/24337083/005c68f6-1267-11e7-9699-dc2d2a692b64.png)

**Comment by jdolan** [comment] 2017-03-27 01:00
Bah, when I resized the image, it became difficult to see the issue. Mine and @kaadmy 's scores are drawn atop one another.

**Comment by Paril** [comment] 2017-03-27 05:31
Well that's weird.

**Comment by Paril** [comment] 2017-03-27 05:43
http://i.imgur.com/mEAwuAy.jpg

Can't reproduce, need more info.

**Comment by kaadmy** [comment] 2017-03-27 16:59
We had spectators when that bug happened, one is to the right of the visible one.

**Comment by Paril** [comment] 2017-03-28 00:10
Ah, that would probably be it then. It might be drawing to draw 2 cols of them.

**Comment by Paril** [comment] 2017-03-28 07:29
Fixed in c5305d8e5c2c0a88da914944de27c2d7e46ece65

**Closed** 2017-03-28 07:29 UTC
Labels: bug:major
