### ISSUE TITLE
using +zoom sets cg_fov to cg_fov_zoom value

### ISSUE THREAD

**Issue by InFerYes** [jdolan/quetoo#89] opened 2014-09-14 19:46 UTC
This happens very often. It's reproducable, but can't give any more clear information besides "zooming a few times". Rebind to other key, same issue. It's as if zoom gets stuck, but the value gets copied from cg_fov_zoom to cg_fov.

Windows 8.1 64bit
Q2W version 0.1.0 x86_64

video here https://www.youtube.com/watch?v=7iuTjwX98oI

**Comment by jdolan** [comment] 2016-01-01 19:51
This appears to have been fixed by the console rewrite. I can't reproduce this, tapping the key bound to +ZOOM as fast as I can, even while running around and shooting.

**Closed by jdolan** 2016-01-01 19:51 UTC
Labels: bug:minor
