### ISSUE TITLE
BSP compiler not communicating with Radiant?

### ISSUE THREAD

**Issue by Dracant** [jdolan/quetoo#420] opened 2017-02-15 04:58 UTC
Get the following error when trying to compile with Radiant.

** ERROR **
Net_Connect: A non-blocking socket operation could not be completed immediately.

Press any key to close..

**Comment by Panjoo** [comment] 2017-02-15 10:12
http://quetoo.org/books/documentation/creating-levels/bsp-compiler

Doing it from Radiant's menu is much more convenient of course, but for compiling I just use .bat files that I put in the Quetoo/bin dir. For a full compile I create a txt file and put this in:

```
quemap -bsp -vis -light maps/mapname.map
pause
```
.. then save as mapwhatever.bat

**Comment by jdolan** [comment] 2017-02-15 13:33
Ah! This was a Windows-only issue, apparently. I've pushed a fix. If you update, please retest and see if the latest Quemap will talk to Radiant.

**Comment by Dracant** [comment] 2017-02-16 05:48
not working.  even when i run command line.
Adding path e:..

----- BSP -----

** ERROR **
AddScriptToStack: Could not load onkey1.map

Press any key to close..
but my bat files says:
quemap -t 4 -bsp -vis -fast -light -extra e:\monkey1.map

**Comment by Panjoo** [comment] 2017-02-16 10:58
Make sure Radiant stores your .map files in _.../Documents/My Games/Quetoo/default/maps_

Change the .bat line to this:
`quemap -t 4 -bsp -vis -fast -light -extra maps/monkey1.map`

=> And put .bat files in your actual game dir, where quemap.exe resides, eg: _E:/Quetoo/bin_.

(if quemap crashes, try -t4 instead of -t 4 )

**Comment by jdolan** [comment] 2017-02-16 12:24
Argh! My path stuff might not handle being at the root of a Windows drive. 

Btw, you should stop passing `-t N` altogether. `quemap` is now smart enough to resolve how many cores you have, and use the appropriate number of threads.

**Comment by jdolan** [comment] 2017-02-16 13:41
@Dracant @Panjoo I've fixed at least a couple more bugs with Quemap input paths as well as Radiant output monitoring.

Could each of you please try to compile a map from your _Documents\My Games\Quetoo\default\maps_ folder via Radiant and let me know how it goes?

**Comment by Panjoo** [comment] 2017-02-16 23:31
I would if I could!
For quite some time now I can't use any of the latest quemap versions. As you know I've never had much luck running the q2wmap/quemap compiler without crashes, for me that thing is jinxed:/.
To compile maps I have to use a precious quemap that I run from a "Jul 20 2016" Quetoo backup. Everything that comes after it just causes appcrashes, so I've learned to live with it. As long as it doesn't affect the final bsp I'll keep using my older compiler. 

I use NetRadiant btw, and the option in preferences _Enable Build Process Monitoring_ must be disabled or any compiler I use stops functioning.

**Comment by Dracant** [comment] 2017-02-16 23:56
Interesting. It had been working for me up until the last update. 

I'll try the latest tonight when I get home.

**Comment by jdolan** [comment] 2017-02-17 01:10
Sounds like this is working as intended again. Yay! @Panjoo would you mind trying this revision, just in case things are working again?

**Closed by jdolan** 2017-02-17 01:10 UTC
Labels: bug:major
