### ISSUE TITLE
Physics bugs on fragpipe

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo#244] opened 2016-10-30 18:34 UTC
I'm unable to walk/run over either of these steps or the ledge on the fragpipe. I'm not sure if this is a recent regression, or just something we all missed because we were to busy jumping around :)

![quetoo027](https://cloud.githubusercontent.com/assets/567688/19838836/a221cfc4-9e94-11e6-811d-a38e7647fde2.png)
![quetoo028](https://cloud.githubusercontent.com/assets/567688/19838837/a230aed6-9e94-11e6-9af7-56dd41e4ab9a.png)

**Comment by jdolan** [comment] 2016-10-30 19:16
600fps? What happens if you clamp your FPS to 60?

**Comment by Panjoo** [comment] 2016-10-31 23:10
Alright, I've just edited the staircases and made them out of 4 steps (of 12 units) instead of 3 (of 16 untis).
Might hide this issue for now and looks somewhat better.
BTW, see screenshot, I tried to clip around the doors of the fragpipe to prevent getting stuck but quetoo don't like clips intersecting with func_entities! I've had the same difficulties with the Red Armor-bridge on Lavatomb. Tried to place a clip over the gap and half the map went kuku.

![bugzbugzbugz](https://cloud.githubusercontent.com/assets/10857572/19874700/75b7a15a-9fc7-11e6-9352-d359a12acf55.jpg)

**Comment by jdolan** [comment] 2016-11-01 03:45
Oh wow. Crazy bug. Do you know of Q2's tools have this issue as well?

As for WickedShell's pmove woes, it's because he's hitting 700fps. At such small frame intervals, pmove does not correctly traverse stairs. I'm addressing this by locking the game and pmove to 60hz, like most modern games do. There's already a branch for this, and the code will be in everyone's hands by this weekend. But I'm glad you broke those stairs up -- I'm sure they look better :)

**Comment by WickedShell** [comment] 2016-11-02 10:14
For the record I haven't been able to reproduce it at crazy high framerates
again (without having changed the build at all, but that evening it was
100% reliable.

**Comment by jdolan** [comment] 2016-11-04 02:52
Please re-test with the latest code. We're locked at 60hz pmove now, so micro-frame moves like what you had before are no longer possible. I think this is fixed.

**Comment by jdolan** [comment] 2016-11-05 13:50
I can approach 500fps on my system, and I can't reproduce this at all. I'm 95% confident this is resolved.

**Closed by jdolan** 2016-11-05 13:50 UTC
Labels: bug:major
